name: e2e

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.10.0"
          image: "kindest/node:v1.20.2"
      - name: Deploy dendrite staging
        run: |
          kustomize build ./dendrite/dev/ | kubectl apply -f -
      - name: Verify dendrite deployment
        run: |
          kubectl wait pods --selector=k8s-app=dendrite --for=condition=ready --timeout=60s
      - name: Debug failure
        if: failure()
        run: |
          kubectl get all
          kubectl get deploy --selector=k8s-app=dendrite
          kubectl logs --selector=k8s-app=dendrite
          kubectl get events
